# Generated by Django 5.0.3 on 2024-07-04 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_data", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
