# Generated by Django 5.0.3 on 2024-07-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_data", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=8)),
            ],
        ),
    ]
