# Generated by Django 5.0.3 on 2024-07-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_data", "0003_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.IntegerField()),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("payment_status", models.CharField(default="Pending", max_length=20)),
                ("shipping_address", models.TextField()),
                ("billing_address", models.TextField()),
                ("payment_method", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api_data.user"
                    ),
                ),
            ],
        ),
    ]
